"""add postgis geometry columns

Revision ID: 8a9b88fed4ce
Revises: 
Create Date: 2026-07-21 19:44:28.515799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '8a9b88fed4ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertising_plans', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('advertising_plans_slug_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_advertising_plans_slug'), ['slug'])
        batch_op.drop_table_comment(
        existing_comment='Merchant subscription plans'
    )

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('idx_audit_logs_user_id'))
        batch_op.drop_table_comment(
        existing_comment='Audit trail for all system actions'
    )

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
        batch_op.add_column(sa.Column('check_in_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
        batch_op.add_column(sa.Column('check_out_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
        batch_op.alter_column('category',
               existing_type=postgresql.ENUM('plumbing', 'electrical', 'carpentry', 'painting', 'tiling', 'masonry', 'welding', 'cleaning', 'laundry', 'shopping', 'errands', 'repair', 'maintenance', 'installation', 'other', name='job_category'),
               type_=sa.Enum('PLUMBING', 'ELECTRICAL', 'CARPENTRY', 'PAINTING', 'TILING', 'MASONRY', 'WELDING', 'CLEANING', 'LAUNDRY', 'SHOPPING', 'ERRANDS', 'REPAIR', 'MAINTENANCE', 'INSTALLATION', 'OTHER', name='jobcategory'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('posted', 'assigned', 'in_progress', 'completed', 'cancelled', 'disputed', name='job_status'),
               type_=sa.Enum('POSTED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='jobstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'posted'::job_status"))
        batch_op.alter_column('estimated_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('final_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('service_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('check_in_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('check_out_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('cancelled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_jobs_category'))
        batch_op.drop_index(batch_op.f('idx_jobs_created_at'))
        batch_op.drop_index(batch_op.f('idx_jobs_customer_id'))
        batch_op.drop_index(batch_op.f('idx_jobs_provider_id'))
        batch_op.drop_index(batch_op.f('idx_jobs_search'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_jobs_status'))
        batch_op.drop_index(batch_op.f('idx_jobs_tracking_code'), postgresql_where='(tracking_code IS NOT NULL)')
        batch_op.drop_constraint(batch_op.f('jobs_tracking_code_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_jobs_location'))
        batch_op.create_index('idx_jobs_location', ['location'], unique=False, postgresql_using='gist', if_not_exists=True)
        batch_op.create_index('idx_jobs_check_in_location', ['check_in_location'], unique=False, postgresql_using='gist', if_not_exists=True)
        batch_op.create_index('idx_jobs_check_out_location', ['check_out_location'], unique=False, postgresql_using='gist', if_not_exists=True)
        batch_op.create_unique_constraint(batch_op.f('uq_jobs_tracking_code'), ['tracking_code'])
        batch_op.drop_table_comment(
        existing_comment='Service jobs posted by customers and assigned to providers'
    )
        batch_op.drop_column('longitude')
        batch_op.drop_column('check_out_latitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('check_out_longitude')
        batch_op.drop_column('check_in_latitude')
        batch_op.drop_column('check_in_longitude')

    with op.batch_alter_table('merchant_analytics', schema=None) as batch_op:
        batch_op.alter_column('revenue',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_merchant_analytics_date'))
        batch_op.drop_index(batch_op.f('idx_merchant_analytics_provider_id'))
        batch_op.drop_constraint(batch_op.f('merchant_analytics_provider_id_date_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('merchant_analytics_provider_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_merchant_analytics_provider_id_providers'), 'providers', ['provider_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Daily analytics for merchant stores'
    )

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('delivered_via',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.alter_column('delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_notifications_is_read'))
        batch_op.drop_index(batch_op.f('idx_notifications_user_id'))
        batch_op.drop_table_comment(
        existing_comment='System notifications for users'
    )
        batch_op.drop_column('metadata')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('platform_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('provider_earnings',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('provider',
               existing_type=postgresql.ENUM('opay', 'paystack', 'flutterwave', name='payment_provider'),
               type_=sa.Enum('OPAY', 'PAYSTACK', 'FLUTTERWAVE', name='paymentprovider'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'held', 'released', 'refunded', 'failed', 'disputed', name='payment_status'),
               type_=sa.Enum('PENDING', 'HELD', 'RELEASED', 'REFUNDED', 'FAILED', 'DISPUTED', name='paymentstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::payment_status"))
        batch_op.alter_column('held_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('released_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('refunded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('failed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_payments_job_id'))
        batch_op.drop_index(batch_op.f('idx_payments_reference'))
        batch_op.drop_index(batch_op.f('idx_payments_status'))
        batch_op.drop_constraint(batch_op.f('payments_reference_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_payments_reference'), ['reference'])
        batch_op.drop_table_comment(
        existing_comment='Payment transactions with escrow support'
    )
        batch_op.drop_column('metadata')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
        batch_op.alter_column('skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.alter_column('hourly_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('portfolio_urls',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.alter_column('rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('total_earnings',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('total_revenue',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_providers_is_available'), postgresql_where='(is_available = true)')
        batch_op.drop_index(batch_op.f('idx_providers_skills'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_providers_slug'), postgresql_where='(slug IS NOT NULL)')
        batch_op.drop_index(batch_op.f('idx_providers_user_id'))
        batch_op.drop_constraint(batch_op.f('providers_slug_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_providers_location'))
        batch_op.create_index('idx_providers_location', ['location'], unique=False, postgresql_using='gist', if_not_exists=True)
        batch_op.create_unique_constraint(batch_op.f('uq_providers_slug'), ['slug'])
        batch_op.drop_table_comment(
        existing_comment='Service provider profiles with skills and verification status'
    )
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_ratings_job_id'))
        batch_op.drop_index(batch_op.f('idx_ratings_target_id'))
        batch_op.drop_table_comment(
        existing_comment='User ratings for providers and customers'
    )

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_refresh_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('idx_refresh_tokens_token'))
        batch_op.drop_index(batch_op.f('idx_refresh_tokens_user_id'))
        batch_op.drop_constraint(batch_op.f('refresh_tokens_token_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_refresh_tokens_token'), ['token'])
        batch_op.drop_constraint(batch_op.f('refresh_tokens_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_refresh_tokens_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='JWT refresh tokens for authentication'
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_bvn'), postgresql_where='(bvn IS NOT NULL)')
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_is_active'), postgresql_where='(is_active = true)')
        batch_op.drop_index(batch_op.f('idx_users_nin'), postgresql_where='(nin IS NOT NULL)')
        batch_op.drop_index(batch_op.f('idx_users_phone'))
        batch_op.drop_index(batch_op.f('idx_users_role'))
        batch_op.drop_constraint(batch_op.f('users_bvn_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_nin_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_phone_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('uq_users_bvn'), ['bvn'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_nin'), ['nin'])
        batch_op.drop_table_comment(
        existing_comment='System users including customers, providers, and admins'
    )

    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('no_show', 'poor_quality', 'theft', 'damage', 'harassment', 'fraud', 'late_arrival', 'incomplete_work', 'bad_communication', 'cancellation', 'other', name='violation_type'),
               type_=sa.Enum('NO_SHOW', 'POOR_QUALITY', 'THEFT', 'DAMAGE', 'HARASSMENT', 'FRAUD', 'LATE_ARRIVAL', 'INCOMPLETE_WORK', 'BAD_COMMUNICATION', 'CANCELLATION', 'OTHER', name='violationtype'),
               existing_nullable=False)
        batch_op.alter_column('severity',
               existing_type=postgresql.ENUM('minor', 'major', 'critical', name='violation_severity'),
               type_=sa.Enum('MINOR', 'MAJOR', 'CRITICAL', name='violationseverity'),
               existing_nullable=True,
               existing_server_default=sa.text("'minor'::violation_severity"))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending_review', 'confirmed', 'dismissed', 'appealed', 'resolved', name='violation_status'),
               type_=sa.Enum('PENDING_REVIEW', 'CONFIRMED', 'DISMISSED', 'APPEALED', 'RESOLVED', name='violationstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending_review'::violation_status"))
        batch_op.alter_column('reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('penalty_type',
               existing_type=postgresql.ENUM('warning', 'suspension', 'ban', 'fine', name='penalty_type'),
               type_=sa.Enum('WARNING', 'SUSPENSION', 'BAN', 'FINE', name='penaltytype'),
               existing_nullable=True)
        batch_op.alter_column('appeal_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_violations_status'))
        batch_op.drop_index(batch_op.f('idx_violations_user_id'))
        batch_op.drop_table_comment(
        existing_comment='Violation reports and accountability tracking'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Violation reports and accountability tracking',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_violations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_violations_status'), ['status'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('appeal_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('penalty_type',
               existing_type=sa.Enum('WARNING', 'SUSPENSION', 'BAN', 'FINE', name='penaltytype'),
               type_=postgresql.ENUM('warning', 'suspension', 'ban', 'fine', name='penalty_type'),
               existing_nullable=True)
        batch_op.alter_column('reviewed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING_REVIEW', 'CONFIRMED', 'DISMISSED', 'APPEALED', 'RESOLVED', name='violationstatus'),
               type_=postgresql.ENUM('pending_review', 'confirmed', 'dismissed', 'appealed', 'resolved', name='violation_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending_review'::violation_status"))
        batch_op.alter_column('severity',
               existing_type=sa.Enum('MINOR', 'MAJOR', 'CRITICAL', name='violationseverity'),
               type_=postgresql.ENUM('minor', 'major', 'critical', name='violation_severity'),
               existing_nullable=True,
               existing_server_default=sa.text("'minor'::violation_severity"))
        batch_op.alter_column('type',
               existing_type=sa.Enum('NO_SHOW', 'POOR_QUALITY', 'THEFT', 'DAMAGE', 'HARASSMENT', 'FRAUD', 'LATE_ARRIVAL', 'INCOMPLETE_WORK', 'BAD_COMMUNICATION', 'CANCELLATION', 'OTHER', name='violationtype'),
               type_=postgresql.ENUM('no_show', 'poor_quality', 'theft', 'damage', 'harassment', 'fraud', 'late_arrival', 'incomplete_work', 'bad_communication', 'cancellation', 'other', name='violation_type'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_table_comment(
        'System users including customers, providers, and admins',
        existing_comment=None
    )
        batch_op.drop_constraint(batch_op.f('uq_users_nin'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_bvn'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_phone_key'), ['phone'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_nin_key'), ['nin'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_bvn_key'), ['bvn'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_nin'), ['nin'], unique=False, postgresql_where='(nin IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_users_is_active'), ['is_active'], unique=False, postgresql_where='(is_active = true)')
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_bvn'), ['bvn'], unique=False, postgresql_where='(bvn IS NOT NULL)')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_table_comment(
        'JWT refresh tokens for authentication',
        existing_comment=None
    )
        batch_op.drop_constraint(batch_op.f('fk_refresh_tokens_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('refresh_tokens_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(batch_op.f('uq_refresh_tokens_token'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('refresh_tokens_token_key'), ['token'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_refresh_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_refresh_tokens_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('idx_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_table_comment(
        'User ratings for providers and customers',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_ratings_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ratings_job_id'), ['job_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Service provider profiles with skills and verification status',
        existing_comment=None
    )
        batch_op.drop_constraint(batch_op.f('uq_providers_slug'), type_='unique')
        batch_op.drop_index('idx_providers_location', postgresql_using='gist')
        batch_op.create_index(batch_op.f('idx_providers_location'), ['latitude', 'longitude'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('providers_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_providers_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_providers_slug'), ['slug'], unique=False, postgresql_where='(slug IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_providers_skills'), ['skills'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_providers_is_available'), ['is_available'], unique=False, postgresql_where='(is_available = true)')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('total_revenue',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('total_earnings',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('portfolio_urls',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.alter_column('hourly_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('skills',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.drop_column('location')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Payment transactions with escrow support',
        existing_comment=None
    )
        batch_op.drop_constraint(batch_op.f('uq_payments_reference'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('payments_reference_key'), ['reference'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_job_id'), ['job_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('failed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('refunded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('released_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('held_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'HELD', 'RELEASED', 'REFUNDED', 'FAILED', 'DISPUTED', name='paymentstatus'),
               type_=postgresql.ENUM('pending', 'held', 'released', 'refunded', 'failed', 'disputed', name='payment_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::payment_status"))
        batch_op.alter_column('provider',
               existing_type=sa.Enum('OPAY', 'PAYSTACK', 'FLUTTERWAVE', name='paymentprovider'),
               type_=postgresql.ENUM('opay', 'paystack', 'flutterwave', name='payment_provider'),
               existing_nullable=False)
        batch_op.alter_column('provider_earnings',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('platform_fee',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('payment_metadata')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'System notifications for users',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_is_read'), ['is_read'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('delivered_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('delivered_via',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.alter_column('read_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.drop_column('notification_metadata')

    with op.batch_alter_table('merchant_analytics', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Daily analytics for merchant stores',
        existing_comment=None
    )
        batch_op.drop_constraint(batch_op.f('fk_merchant_analytics_provider_id_providers'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('merchant_analytics_provider_id_fkey'), 'providers', ['provider_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('merchant_analytics_provider_id_date_key'), ['provider_id', 'date'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_merchant_analytics_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_merchant_analytics_date'), ['date'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('revenue',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('check_in_latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('check_out_longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('check_out_latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=False))
        batch_op.create_table_comment(
        'Service jobs posted by customers and assigned to providers',
        existing_comment=None
    )
        batch_op.drop_constraint(batch_op.f('uq_jobs_tracking_code'), type_='unique')
        batch_op.drop_index('idx_jobs_check_out_location', postgresql_using='gist')
        batch_op.drop_index('idx_jobs_check_in_location', postgresql_using='gist')
        batch_op.drop_index('idx_jobs_location', postgresql_using='gist')
        batch_op.create_index(batch_op.f('idx_jobs_location'), ['latitude', 'longitude'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('jobs_tracking_code_key'), ['tracking_code'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_jobs_tracking_code'), ['tracking_code'], unique=False, postgresql_where='(tracking_code IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_search'), [sa.literal_column("to_tsvector('english'::regconfig, (((((COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(city, ''::character varying)::text) || ' '::text) || COALESCE(state, ''::character varying)::text)")], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_jobs_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_created_at'), [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_category'), ['category'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('cancelled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('check_out_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('check_in_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('service_fee',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('final_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('estimated_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('POSTED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='jobstatus'),
               type_=postgresql.ENUM('posted', 'assigned', 'in_progress', 'completed', 'cancelled', 'disputed', name='job_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'posted'::job_status"))
        batch_op.alter_column('category',
               existing_type=sa.Enum('PLUMBING', 'ELECTRICAL', 'CARPENTRY', 'PAINTING', 'TILING', 'MASONRY', 'WELDING', 'CLEANING', 'LAUNDRY', 'SHOPPING', 'ERRANDS', 'REPAIR', 'MAINTENANCE', 'INSTALLATION', 'OTHER', name='jobcategory'),
               type_=postgresql.ENUM('plumbing', 'electrical', 'carpentry', 'painting', 'tiling', 'masonry', 'welding', 'cleaning', 'laundry', 'shopping', 'errands', 'repair', 'maintenance', 'installation', 'other', name='job_category'),
               existing_nullable=False)
        batch_op.drop_column('check_out_location')
        batch_op.drop_column('check_in_location')
        batch_op.drop_column('location')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Audit trail for all system actions',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('advertising_plans', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Merchant subscription plans',
        existing_comment=None
    )
        batch_op.drop_constraint(batch_op.f('uq_advertising_plans_slug'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('advertising_plans_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
